apiVersion: apps/v1
kind: Deployment
metadata:
  name: bernardoalmeida-playlist-recommender-deployment
  namespace: bernardoalmeida
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bernardoalmeida-playlist-recommender
  template:
    metadata:
      labels:
        app: bernardoalmeida-playlist-recommender
    spec:
      volumes:
      - name: bernardoalmeida-playlist-recommender-storage
        persistentVolumeClaim:
          claimName: bernardoalmeida-playlist-recommender-pvc
      containers:
      - name: bernardoalmeida-playlist-recommender-model
        image: docker.io/bereis01/playlist-recommender-model:latest
        volumeMounts:
        - mountPath: "/usr/data"
          name: bernardoalmeida-playlist-recommender-storage
      - name: bernardoalmeida-playlist-recommender-backend
        image: docker.io/bereis01/playlist-recommender-backend:latest
        volumeMounts:
        - mountPath: "/usr/data"
          name: bernardoalmeida-playlist-recommender-storage