apiVersion: v1
kind: ConfigMap
metadata:
  name: bernardoalmeida-playlist-recommender-configmap
  namespace: bernardoalmeida
data:
  MODEL_PATH: "/usr/data/test.pkl"
  DATABASE_PATH: "/usr/data/2023_spotify_ds1.csv"