apiVersion: apps/v1
kind: Deployment
metadata:
  name: bernardoalmeida-playlist-recommender-deployment
  namespace: bernardoalmeida
spec:
  replicas: 3
  selector:
    matchLabels:
      app: bernardoalmeida-playlist-recommender
  template:
    metadata:
      labels:
        app: bernardoalmeida-playlist-recommender
    spec:
      volumes:
      - name: bernardoalmeida-playlist-recommender-storage
        persistentVolumeClaim:
          claimName: bernardoalmeida-playlist-recommender-pvc
      containers:
      - name: bernardoalmeida-playlist-recommender-backend
        image: docker.io/bereis01/playlist-recommender-backend:latest
        env:
        - name: MODEL_PATH
          value: "/usr/data/test.pkl"
        - name: FORCE
          value: "WAAAAAAAAAAA"
        volumeMounts:
        - mountPath: "/usr/data"
          name: bernardoalmeida-playlist-recommender-storage